ayobeli_asp/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ayobeli_asp.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
												ViewBag.BrowserWidth = Request.Browser.ScreenPixelsWidth;
												return View();
        }

								public ActionResult Error(int id)
								{
												ViewBag.ErrorCode = id == 502 ? id : 404;
												ViewBag.Message = id == 502 ? StringResource.ErrorBadGateway : StringResource.ErrorPageNotFound;
												return View();
								}
    }
}

ayobeli_asp/Controllers/UserController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using CustomSecurity;
using System.Net.Mail;
using System.Net;
using ayobeli_asp.Models;

namespace ayobeli_asp.Controllers
{
    public class UserController : Controller
    {

								public ActionResult Register()
								{
												return View();
								}

								[HttpPost]
								[ValidateAntiForgeryToken]
								public ActionResult Register([Bind(Exclude = "isEmailVerified, Activation")] User user)
        {
												if (ModelState.IsValid)
												{
																if (IsEmailExist(user.Email))
																{
																				ModelState.AddModelError("Email", "* alamat email sudah terdaftar");
																				return View(user);
																}

																// fill user data
																user.Activation = Guid.NewGuid();
																user.Password = Security.GetHashedSensitive(user.Password);
																user.ConfirmPassword = user.Password;
																user.Role = "normal";
																user.Verified = false;
															
																// save user to db
																var db = new AyobeliDBEntities();
																db.Users.Add(user);
																// db.Configuration.ValidateOnSaveEnabled = false
																db.SaveChanges();
																SendVerificationEmailLink(user.Email, user.Activation.ToString());

																ViewBag.CoreMessage = StringResource.RegisterSuccessTopMessage;
																ViewBag.SupplementaryMessage = StringResource.RegisterSuccessExplanation;
																return View("Success");
												}

												return View(user);
								}
								public ActionResult Success()
								{
												return View();
								}

								[HttpGet]
								public ActionResult VerifyAccount(string id)
								{
												bool isValidRequest = false;
												using (AyobeliDBEntities db = new AyobeliDBEntities())
												{
																var user = db.Users.Where(u => u.Activation == new Guid(id)).FirstOrDefault();
																if (user != null)
																{
																				user.Verified = true;
																				user.Activation = null;
																				isValidRequest = true;
																				db.SaveChanges();
																}
												}
												
												return View();
								}

								[HttpPost]
								[ValidateAntiForgeryToken]
								public ActionResult Login()
								{
												return View();
								}

								[NonAction]
								private bool IsEmailExist(string email)
								{
												AyobeliDBEntities db = new AyobeliDBEntities();
												var user = db.Users.Where(u => u.Email == email).FirstOrDefault();
												return user != null;
								}

								[NonAction]
								private void SendVerificationEmailLink(string userEmail, string activationCode)
								{
												string verifyUrl = "/User/VerifyAccount/" + activationCode;
												string link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

												var AyoBeliEmail = new MailAddress(StringResource.EmailAccount, "AyoBeli");
												var AyoBeliPassword = StringResource.EmailPassword;

												var receiver = new MailAddress(userEmail);
												string subject = StringResource.VerifyEmailSubject;
												string body = String.Format(StringResource.VerifyEmailBody, link);

												var emailClient = new SmtpClient
												{
																Host = "smtp.gmail.com",
																Port = 587,
																EnableSsl = true,
																DeliveryMethod = SmtpDeliveryMethod.Network,
																UseDefaultCredentials = false,
																Credentials = new NetworkCredential(AyoBeliEmail.Address, AyoBeliPassword)
												};

												using (var message = new MailMessage(AyoBeliEmail, receiver)
												{
																Subject = subject,
																Body = body,
																IsBodyHtml = true
												})
												emailClient.Send(message);
								}
    }
}

ayobeli_asp/Views/Shared/Base.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
				<meta name="viewport" content="width=device-width" />
				<title>@ViewBag.Title - AyoBeli</title>
				@Styles.Render("~/content/site")
				@Scripts.Render("~/Scripts/modernizr-2.6.2.js")
</head>
<body>
    @RenderBody()
</body>

@RenderSection("Scripts", required: false)
</html>

ayobeli_asp/Views/Shared/_Header.cshtml
@{
    Layout = null;
}

<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top" role="navigation">
				@Html.ActionLink("AyoBeli", "Index", "Default", null, new { @class = "navbar-brand" })
				<!-- toggle button -->
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible">
								<span class="navbar-toggler-icon"></span>
				</button>

				<ul class="navbar-nav d-none d-md-block">
								<li class="nav-item dropdown">
												<a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
																Kategori
												</a>
												<div class="dropdown-menu">
																<a class="dropdown-item" href="#">Link 1</a>
																<a class="dropdown-item" href="#">Link 2</a>
																<a class="dropdown-item" href="#">Link 3</a>
												</div>
								</li>
				</ul>
				<form class="mx-2 my-auto w-50 d-none d-md-block">
								<div class="input-group">
												<input type="text" class="form-control" placeholder="Cari barang">
												<span class="input-group-btn">
																<button class="btn btn-outline-secondary" type="button">Cari</button>
												</span>
								</div>
				</form>
				<div class="collapse navbar-collapse navbar-left" id="collapsible">
								@if (User.Identity.IsAuthenticated)
								{

								}
								else
								{
												<ul class="nav navbar-nav ml-auto">
																<li class="nav-item">
																				@Html.ActionLink("Daftar", "Register", "User", null, new { @class = "nav-link"})
																</li>
																<li class="nav-item dropdown">
																				<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Login</a>
																				<div class="dropdown-menu dropdown-menu-right" id="login-desktop">
																								@using (Html.BeginForm("Login", "User", FormMethod.Post, new { @class = "form-horizontal" }))
																								{
																												@Html.AntiForgeryToken()
																												<input id="sp_uname" class="form-control login" type="text" name="sp_uname" placeholder="Username.." />
																												<input id="sp_pass" class="form-control login" type="password" name="sp_pass" placeholder="Password.." />
																												<br />
																												<input class="btn btn-primary btn-block" type="submit" name="submit" value="login" />
																								}
																				</div>
																</li>
												</ul>
								}
				</div>
</nav>

<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top  d-md-none">
				<form class="w-100">
								<div class="input-group">
												<input type="text" class="form-control" placeholder="Cari barang">
												<span class="input-group-btn">
																<button class="btn btn-outline-secondary" type="button">Cari</button>
												</span>
								</div>
				</form>>
</nav>
<br>

ayobeli_asp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AyoBeli</title>
    @Styles.Render("~/content/site")
				@Scripts.Render("~/Scripts/modernizr-2.6.2.js")
</head>
<body>
			@{ Html.RenderPartial("_Header"); }
    
    <div class="container body-content">
        @RenderSection("Content")
        <hr />
    </div>

				<footer class="footer">
								<div class="container">
												<p>&copy; @DateTime.Now.Year - AyoBeli </p>
								</div>
				</footer>

    @Scripts.Render("~/bundles/jquery-w-bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>